Transform: AWS::Serverless-2016-10-31

Parameters:
  PrefixGitHubRepository:
    Type: String

Resources:
  RoleGithubActionsAdministrator:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${PrefixGitHubRepository}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  BucketTerraformStates:
    Type: AWS::S3::Bucket

  TableTerraformLocks:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: LockID
        Type: String

Outputs:
  TableNameTerraformLocks:
    Value: !Ref TableTerraformLocks

  BucketNameTerraformStates:
    Value: !Ref BucketTerraformStates

  RoleArnGithubActionsAdministrator:
    Value: !GetAtt RoleGithubActionsAdministrator.Arn
